---
title: 'Books I read in 2023'
author: "Jason Collins"
date: 2024-01-18 14:00:00+10:00
draft: false
---

These are the books I enjoyed the most in 2023, although they were published in different years:

- Edward Abbey, *Desert Solitaire*: I love the sense of place that Abbey creates.
- Paige Harden, *The Genetic Lottery*: Harden's politics seep through the text, and it is slightly irritating to be constantly labelled a eugenicist. However, it contains an accessible explanation of the science with many great examples.
- Ray Bradbury, *The Martian Chronicles*: I bought it for the kids, but I suspect it's beyond them. Wonderful stories.

The book I invested in the most was Douglas Hofstadter's, *Godel, Escher, Bach*. It was a good book to work through during 12 days of surfing on an isolated island. Too much clever for the sake of being clever and an unclear thesis (even after reading the 20-year anniversary foreword that stated what the thesis was), but enough interesting ideas to keep me going.

Below is the list of books I read in 2023 (with a star if I have read them before). For the first time in a few years, the volume of my reading of books cover-to-cover has increased, with 36 total (23 non-fiction, 13 fiction).

*Non-Fiction*

- Edward Abbey, *Desert Solitaire*
- Peter Attia, *Outlive: The Science and Art of Longevity*
- Jordan Belfort, *The Wolf of Wall Street*
- Dale Bredesen, *The End of Alzheimer's*
- Janet Browne, *Charles Darwin: Voyaging*\*
- Janet Browne, *Charles Darwin: The Power of Place*
- Ross Douthat, *The Decadent Society*
- Dave Grohl, *The Storyteller: Tales of Life and Music*
- Paige Harden, *The Genetic Lottery*
- Douglas Hofstadter, *Godel, Escher, Bach*
- Chuck Klosterman, *The Nineties*
- Jon Krakuer, *Into Thin Air*
- Michael Lewis, *Liar's Poker*\*
- John List, *The Voltage Effect*
- Andrew Lo, *Adaptive Markets*
- Gordon Menzies, *Western Fundamentalism*
- Douglas Murray, *The War on the West*
- Benjamin Newell, David Lagnado and David Shanks, *Straight Choices: The Psychology of Decision Making*
- Jenny Odell, *Saving Time*
- Lionel Page, *Optimally Irrational*
- Richard Reeves, *Of Boys and Men*
- Richard Thaler, *The Winner's Curse*
- Richard Wrangham, *Catching Fire*

*Fiction*

- Edward Abbey, *The Monkeywrench Gang*
- Edward Abbey, *Fire on the Mountain*
- Ray Bradbury, *The Martian Chronicles*
- Douglas Coupland, *Generation X*\*
- Aldous Huxley, *Brave New World*
- George RR Martin, *A Dance with Dragons*
- George RR Martin, *A Feast for Crows*
- Baroness Orczy, *The Scarlet Pimpernel*
- George Orwell, *1984*
- Robert Louis Stevenson, *Treasure Island*\*
- JRR Tolkein, *The Fellowship of the Ring*\*
- JRR Tolkein, *The Two Towers*\*
- JRR Tolkein, *The Return of the King*\*


Previous annual book lists: [2010](/posts/top-10-books-in-2010.md), [2011](/posts/best-books-i-read-in-2011.md), [2012](/posts/the-best-books-i-read-in-2012.md), [2013](/posts/best-books-i-read-in-2013.md), [2014](/posts/best-books-i-read-in-2014.md), [2015](/posts/best-books-i-read-in-2015.md), [2016](/posts/best-books-i-read-in-2016.md), [2017](/posts/best-books-i-read-in-2017.md), [2018](/posts/books-i-read-in-2018.md), [2019](/posts/best-books-i-read-in-2019.md), [2020](/posts/best-books-i-read-in-2020.md), [2021](/posts/best-books-i-read-in-2021.md), [2022](/posts/best-books-i-read-in-2022.md)
