---
title: 'Books I read in 2024'
author: "Jason Collins"
date: 2025-01-17 17:00:00+10:00
draft: false
---

The books I enjoyed the most in 2024, although all were published in different years:

- Ashlee Vance, *When the Heavens Went on Sale*: For all the grumbling about how progress in software isn't matched in the physical world, Vance tells some amazing stories. The tale about how Planet Labs got going using smartphone technology to make shoebox size satellites was fantastic.
- Julia Galef, *The Scout Mindset: Why Some People See Things Clearly and Others Don't*: Wonderfully practical. I enter almost every psychology or behavioural science related book dreading the shaky scientific studies I will be dragged through. But Galef did a great job of knowing when to pull out a study (not often) and when to build a more practical case.
- William Poundstone, *Fortune's Formula: The Untold Story of the Scientific Betting System That Beat the Casinos and Wall Street*: A good balance of technicality and colour.
- Kurt Vonnnegut, *Player Piano*: Simply a great story.

Below is the list of books I read in 2024 (with a star if I have read them before). My volume of my reading of books cover-to-cover has increased from 2023, with 49 total (26 non-fiction, 23 fiction).

*Non-Fiction*

- Kathryn Astbury and Robert Plomin, *G is for Genes: The Impact of Genetics on Education and Achievement*
- Eric Berger, *Liftoff: Elon Musk and the Desperate Early Days that Launched SpaceX*
- Eric Berger, *Reentry: SpaceX, Elon Musk, and the Reusable Rockets that Launched a Second Space Age*
- Dalton Conley and Jason Fletcher, *The Genome Factor: What the Social Genomics Revolution Reveals about Ourselves, Our History, and the Future*
- Tyler Cowen and Daniel Gross, *Talent: How to Identify Energizers, Creatives and Winners Around the World*
- Kate Crawford, *Atlas of AI: Power, Politics, and the Planetary Costs of Artificial Intelligence*
- Nir Eyal, *Indistractable: How to Control Your Attention and Choose Your Life*
- Bent Flyvbjerg and Dan Gardner, *How Big Things Get Done*
- Martin Ford, *Architects of Intelligence*
- Julia Galef, *The Scout Mindset: Why Some People See Things Clearly and Others Don't*
- Michael Greger, *How Not to Age*
- Saul Griffith, *Electrify: An Optimist's Playbook for Our Clean Energy Future*
- Kathryn Paige Harden, *The Genetic Lottery: Why DNA Matters for Social Equality* \*
- Michel Lewis, *Going Infinite: The Rise and Fall of a New Tycoon*
- Ethan Mollick, *Co-Intelligence: Living and Working with AI*
- Charles Murray, *Human Diversity: The Biology of Gender, Race and Class*
- Cal Newport, *Slow Productivity*
- Toby Ord, "The Precipice: Existential Risk and the Future of Humanity"
- Robert Plomin, *Blueprint: How DNA makes us who we are*
- William Poundstone, *Fortune's Formula: The Untold Story of the Scientific Betting System That Beat the Casinos and Wall Street*
- Nichola Raihani, *The Social Instinct*
- Rebecca Reider, *Dreaming the Biosphere*
- Edward O Thorpe, *A Man for All Markets: Beating the Odds from Las Vegas to Wall Street*
- Ashlee Vance, *When the Heavens Went on Sale*
- Walter Willett, *Eat, Drink and Be Healthy*
- Scott H Young, *Get Better at Anything*

*Fiction*

- Edward Abbey, *The Brave Cowboy*
- Isaac Asimov, *I, Robot*
- Isaac Asimov, *The Caves of Steel*
- Isaac Asimov, *The Naked Sun*
- Isaac Asimov, *The Robots of Dawn*
- Isaac Asimov, *The Complete Robot*
- Isaac Asimov, *Robots and Empire*
- Margaret Atwood, *The Handmaid's Tale* \*
- Orson Scott Card, *Ender's Game*
- Orson Scott Card, *Speaker for the Dead*
- Ernest Cline, *Ready Player One*
- Philip K Dick, *Do Androids Dream of Electric Sheep*
- Robert Heinlein, *Starship Troopers*
- Daniel Keyes, *Flowers for Algernon*
- Madeleine L'Engle, *A Wrinkle in Time*
- Madeleine L'Engle, *A Wind in the Door*
- Madeleine L'Engle, *A Swiftly Tilting Planet*
- John le Carrè, *A Perfect Spy* \*
- Cormac McCarthy, *Stella Maris*
- Cormac McCarthy, *The Passenger*
- Richard Matheson, *I Am Legend*
- Walter Tevis, *The Queen's Gambit* \*
- Kurt Vonnnegut, *Player Piano*


Previous annual book lists: [2010](/posts/top-10-books-in-2010/), [2011](/posts/best-books-i-read-in-2011/), [2012](/posts/the-best-books-i-read-in-2012/), [2013](/posts/best-books-i-read-in-2013/), [2014](/posts/best-books-i-read-in-2014/), [2015](/posts/best-books-i-read-in-2015/), [2016](/posts/best-books-i-read-in-2016/), [2017](/posts/best-books-i-read-in-2017/), [2018](/posts/books-i-read-in-2018/), [2019](/posts/best-books-i-read-in-2019/), [2020](/posts/best-books-i-read-in-2020/), [2021](/posts/best-books-i-read-in-2021/), [2022](/posts/best-books-i-read-in-2022/), [2023](/posts/books-i-read-in-2023/)
