---
title: "Chimps 1, Humans 0"
author: "Jason Collins"
date: 2012-05-16 10:34:01+00:00
draft: false
aliases:
  - /chimps-1-humans-0
---

*See an update [here](https://www.jasoncollins.blog/humans-1-chimps-0-correcting-the-record).*

At the recent [The Biological Basis of Preferences and Behaviour](https://www.jasoncollins.blog/the-biological-basis-of-preferences-and-behaviour-conference/) conference, Colin Camerer presented the results of a paper about work he and his co-authors had done on chimpanzees at the Primate Research Institute at Kyoto University.

At the beginning of the presentation, Camerer showed a couple of videos of experiments dealing with the working memories of chimps. The videos show subjects undergoing a test in which they see five numbers briefly flash on a screen before the numbers are covered with white boxes. The subject must then press the boxes in the order of the numerals. Of the three videos below, the first is a human subject, the second and third a chimpanzee. The chimpanzee (Ayumu) is receiving pieces of apple for each correct answer, which he is collecting from the lower right of the screen.

While the contrast between the first two videos is striking, the third video shows the power of the snapshot that Ayumu has in his mind.

More on this work can be found in [Current Biology](https://doi.org/10.1016/j.cub.2007.10.027).

### Human

{{< video https://youtu.be/RnJTwKMCvqM >}}

### Chimp

{{< video https://youtu.be/iT0abyAIyY8 >}}

### Distracted chimp

{{< video https://youtu.be/mgoIPIQcJ88 >}}

*Jeff Ely beat me to putting up these videos over at [Cheap Talk](http://cheaptalk.org/2012/05/11/chimpanzees-think-faster-than-humans/), but since I already had the post put together, it's still worth a share.
